### ISSUE TITLE
Check if `tmp` files are deleted

### ISSUE THREAD

**Issue by radumarias** [xoriors/rencfs#107]
We are creating tmp files when we create a new file for ex or when e rename or move one. In those cases tmp files are create in tmp OS dependent folder (`/tmp` on Linux for ex.).
We need to check if those get deleted after operation completes or at least when the process finishes.

Test case
- start the cli
- create several files
- rename
- write content
- delete some, but not all
- check those there is no data in `/tmp` of in OS specific tmp folder

**Comment by srzamfir** [comment]
Not sure what this is about ... can you add more context? I've tried the following :
* run cli on specific mount_dir + data_dir
* create temp files with `mktemp` on the mount_dir
* check data_dir/inodes : total number of inodes matches the number of files in fs
* remove temp files from mount_dir : logs show call on release with corresponding inode entries
* check data_dir/inodes : the number of inodes decreased accordingly 
* kill cli : unmount successful 
* restart cli : mount successful and mount_dir contains expected entries

**Comment by srzamfir** [comment]
So i did a little more digging and i don't really see the problem here. I couldn't find anything in the codebase that touches /tmp. 
There are indeed some situations where certain programs such as: vim, libre office, curl,or even mv might cache something in `/tmp`. 
For example i tried creating a libre office file in a rencfs mounted directory and this indeed created something in `/tmp` but that was done by libre office so my expectation was that it also cleans up after itself. 
Vim was a bit more interesting ... it created a temp file directly in the rencfs mounted directory (i see this as expected behavior). 
I also tried mv, cp , curl on several files with sizes ranging from 50MB to 1GB and got nothing. 

If an external program tries to access a rencfs mounted directory and creates some `tmp` files the expectation is that the external program cleans up these temporarily allocated resources as it uses the default filesystem under which it runs. Rencfs just handles any requests related to this mount directory and flushes the actual data under the provided data_dir.

**Comment by radumarias** [comment]
@srzamfir I added test case to desc
